// Sidebar
export const SIDEBAR_OPEN = "SIDEBAR_OPEN";
export const SIDEBAR_CLOSE = "SIDEBAR_CLOSE";
// Professions
export const GET_PROFESSIONS = "GET_PROFESSIONS";
export const GET_PROFESSIONS_SUCCESS = "GET_PROFESSIONS_SUCCESS";
export const GET_PROFESSIONS_ERROR = "GET_PROFESSIONS_ERROR";
